- id: shellcheck-system
  name: find bugs in your shell scripts.
  description: statically checks your shell scripts for errors & potential bugs
  entry: shellcheck
  language: system
  types:
    - shell

- id: shfmt-system
  name: Format your shell scripts.
  description: Unclutter your Shell scripts with shfmt!
  entry: shfmt
  language: system
  types:
    - shell
