- id: shellcheck-system
  name: find bugs in your shell scripts.
  description: statically checks your shell scripts for errors & potential bugs
  entry: shellcheck
  language: system
  types:
    - shell
