name: Code Quality Checks

on: push

jobs:
  codeQualityChecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Prettier to format code
        uses: actionsx/prettier@v3
        with:
          args: --write .
