name: Code Quality Checks

on: push

jobs:
  codeQualityChecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - names: Run Prettier to format code
        uses: actionsx/prettier@v2
        with:
          args: --write .
